### ISSUE TITLE
Nothing -> Keep/Remove

### ISSUE THREAD

**Issue by mitchellwrosen** [nikita-volkov/focus#3]
Hi, just curious - do you know of any examples where a `Strategy` is passed `Nothing`, but the library wants to interpret `Keep` and `Remove` differently?

It seems to me that when given `Nothing`, `Keep`/`Remove` become synonyms, as there is no focused element.

If so, should this be prevented by the library? The first solution that comes to mind (and it's not a very good one) is:

```haskell
data Found s a where
  Found :: a -> Found s a -- like Just
  Missing :: Found False a -- like Nothing

data Decision s a where
  Keep :: Decision s a
  Remove :: Decision True a
  Replace :: a -> Decision s a
```

Thus, `Missing -> Remove` is revented by `True ~ False` being unsatisfiable, but all other combinations type check.

**Comment by mitchellwrosen** [comment]
A not so complicated alternative:

``` haskell
type Strategy a r = (IfExists a r, IfMissing a r)
type IfExists a r = a -> (r, Decision a)
type IfMissing a r = (r, Maybe a) -- Nothing means Keep, Just means Replace
```

**Comment by nikita-volkov** [comment]
The second option is clearly the winner, however what you're trying to solve I can't recognise an issue. Restricting the API in such a way will not increase the safety (in a sense of reducing the possible ways a user could mess up), however it will complicate things.
